In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import metrics

In [2]:
df =pd.read_csv('forestfires.csv')
df

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [4]:
df.describe()

FFMC         DMC          DC         ISI        temp          RH  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean    90.644681  110.872340  547.940039    9.021663   18.889168   44.288201   
std      5.520111   64.046482  248.066192    4.559477    5.806625   16.317469   
min     18.700000    1.100000    7.900000    0.000000    2.200000   15.000000   
25%     90.200000   68.600000  437.700000    6.500000   15.500000   33.000000   
50%     91.600000  108.300000  664.200000    8.400000   19.300000   42.000000   
75%     92.900000  142.400000  713.900000   10.800000   22.800000   53.000000   
max     96.200000  291.300000  860.600000   56.100000   33.300000  100.000000   

             wind        rain         area      dayfri  ...    monthdec  \
count  517.000000  517.000000   517.000000  517.000000  ...  517.000000   
mean     4.017602    0.021663    12.847292    0.164410  ...    0.017408   
std      1.791653    0.295959    63.655818    0.371006  ...    0.130913   
min      0.400000    0.000000     0.000000    0.000000  ...    0.000000   
25%      2.700000    0.000000     0.000000    0.000000  ...    0.000000   
50%      4.000000    0.000000     0.520000    0.000000  ...    0.000000   
75%      4.900000    0.000000     6.570000    0.000000  ...    0.000000   
max      9.400000    6.400000  1090.840000    1.000000  ...    1.000000   

         monthfeb    monthjan    monthjul    monthjun    monthmar    monthmay  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     0.038685    0.003868    0.061896    0.032882    0.104449    0.003868   
std      0.193029    0.062137    0.241199    0.178500    0.306138    0.062137   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         monthnov    monthoct    monthsep  
count  517.000000  517.000000  517.000000  
mean     0.001934    0.029014    0.332689  
std      0.043980    0.168007    0.471632  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      0.000000    0.000000    1.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 28 columns]

In [5]:
df['size_category'].value_counts()

small    378
large    139
Name: size_category, dtype: int64

In [16]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
df['size_category']=label_encoder.fit_transform(df['size_category'])
df['day']=label_encoder.fit_transform(df['day'])

In [17]:
df

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct    5  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov    5  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0              1  
1           0              1  
2           0              1  
3           0              1  
4           0              1  
..        ...            ...  
512         0              0  
513         0              0  
514         0              0  
515         0              1  
516         0              1  

[517 rows x 31 columns]

In [18]:
df = df.drop(['month'],axis=1)
df

day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  ...  \
0      0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00  ...   
1      5  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00  ...   
2      2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00  ...   
3      0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00  ...   
4      3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00  ...   
..   ...   ...    ...    ...   ...   ...  ..   ...   ...    ...  ...   
512    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44  ...   
513    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29  ...   
514    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16  ...   
515    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00  ...   
516    5  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00  ...   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  size_category  
0           0         0              1  
1           1         0              1  
2           1         0              1  
3           0         0              1  
4           0         0              1  
..        ...       ...            ...  
512         0         0              0  
513         0         0              0  
514         0         0              0  
515         0         0              1  
516         0         0              1  

[517 rows x 30 columns]

In [20]:
x= df.iloc[:,0:29]



In [21]:
x

day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  ...  \
0      0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00  ...   
1      5  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00  ...   
2      2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00  ...   
3      0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00  ...   
4      3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00  ...   
..   ...   ...    ...    ...   ...   ...  ..   ...   ...    ...  ...   
512    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44  ...   
513    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29  ...   
514    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16  ...   
515    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00  ...   
516    5  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00  ...   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
0           0         0         0         0         0         1         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         0         1         0   
4           0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         0   

     monthnov  monthoct  monthsep  
0           0         0         0  
1           0         1         0  
2           0         1         0  
3           0         0         0  
4           0         0         0  
..        ...       ...       ...  
512         0         0         0  
513         0         0         0  
514         0         0         0  
515         0         0         0  
516         1         0         0  

[517 rows x 29 columns]

In [22]:
y = df['size_category']

In [23]:
y

0      1
1      1
2      1
3      1
4      1
      ..
512    0
513    0
514    0
515    1
516    1
Name: size_category, Length: 517, dtype: int64

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state=42)

In [27]:
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [28]:
gsv.best_params_ , gsv.best_score_ # BEST PARAMEERS

({'C': 15, 'gamma': 50, 'kernel': 'rbf'}, 0.7365047233468286)

In [31]:
clf = SVC(C= 15, gamma = 50) # soft margin change cost values
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 73.07692307692307


array([[ 0, 35],
       [ 0, 95]], dtype=int64)

In [32]:
clf = SVC(kernel= "linear") 
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)    

Accuracy = 98.46153846153847


array([[33,  2],
       [ 0, 95]], dtype=int64)

In [33]:
clf = SVC(kernel= "poly") 
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)    

Accuracy = 76.92307692307693


array([[ 5, 30],
       [ 0, 95]], dtype=int64)

In [34]:
clf = SVC(kernel= "sigmoid") 
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)    

Accuracy = 70.76923076923077


array([[ 7, 28],
       [10, 85]], dtype=int64)

In [35]:
clf = SVC(kernel= "rbf") 
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)    

Accuracy = 74.61538461538461


array([[ 2, 33],
       [ 0, 95]], dtype=int64)